Vagrant.configure("2") do |config|
  
  config.vm.box = 'centos/7'
  config.vm.hostname = 'jenkins'
  config.vm.network 'forwarded_port', guest: 8080, host: 8080, hostip: '192.168.15.30'
  config.vm.network 'forwarded_port', guest: 8091, host: 8091, hostip: '192.168.15.60'
  config.vm.network "public_network", ip: "192.168.15.30"
  config.vm.network "public_network", ip: "192.168.15.60"
  config.vm.provision 'shell', path: 'provision.sh'
  config.vm.provider 'virtualbox' do |v| 
    v.memory =3000
  end
  
end